## Clock signal
set_property PACKAGE_PIN W5 [get_ports Clk]
	set_property IOSTANDARD LVCMOS33 [get_ports Clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports Clk]

## Switches
set_property PACKAGE_PIN V17 [get_ports {SW[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property PACKAGE_PIN V16 [get_ports {SW[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property PACKAGE_PIN W16 [get_ports {SW[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
#set_property PACKAGE_PIN W17 [get_ports {sw[3]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {Twos_Complement_Switch}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Twos_Complement_Switch}]
set_property PACKAGE_PIN T1 [get_ports {Step_Mode_Switch}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Step_Mode_Switch}]
set_property PACKAGE_PIN R2 [get_ports {Mode_Switch}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Mode_Switch}]


# LEDs
set_property PACKAGE_PIN U16 [get_ports {Reg_7_Out[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[0]}]
set_property PACKAGE_PIN E19 [get_ports {Reg_7_Out[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[1]}]
set_property PACKAGE_PIN U19 [get_ports {Reg_7_Out[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[2]}]
set_property PACKAGE_PIN V19 [get_ports {Reg_7_Out[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[3]}]
set_property PACKAGE_PIN W18 [get_ports {Reg_7_Out[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[4]}]
set_property PACKAGE_PIN U15 [get_ports {Reg_7_Out[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[5]}]
set_property PACKAGE_PIN U14 [get_ports {Reg_7_Out[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[6]}]
set_property PACKAGE_PIN V14 [get_ports {Reg_7_Out[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[7]}]
set_property PACKAGE_PIN V13 [get_ports {Reg_7_Out[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[8]}]
set_property PACKAGE_PIN V3 [get_ports {Reg_7_Out[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[9]}]
set_property PACKAGE_PIN W3 [get_ports {Reg_7_Out[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[10]}]
set_property PACKAGE_PIN U3 [get_ports {Reg_7_Out[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {Overflow}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Overflow}]
set_property PACKAGE_PIN L1 [get_ports {Zero}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Zero}]


#7 segment display
set_property PACKAGE_PIN W7 [get_ports {Seg_7_Out[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[0]}]
set_property PACKAGE_PIN W6 [get_ports {Seg_7_Out[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[1]}]
set_property PACKAGE_PIN U8 [get_ports {Seg_7_Out[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[2]}]
set_property PACKAGE_PIN V8 [get_ports {Seg_7_Out[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[3]}]
set_property PACKAGE_PIN U5 [get_ports {Seg_7_Out[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[4]}]
set_property PACKAGE_PIN V5 [get_ports {Seg_7_Out[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[5]}]
set_property PACKAGE_PIN U7 [get_ports {Seg_7_Out[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[6]}]

set_property PACKAGE_PIN V7 [get_ports {Seg_7_Out[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg_7_Out[7]}]

set_property PACKAGE_PIN U2 [get_ports {Anode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports Reset]
	set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN T18 [get_ports Step_Button]
	set_property IOSTANDARD LVCMOS33 [get_ports Step_Button]
#set_property PACKAGE_PIN W19 [get_ports btnL]
	#set_property IOSTANDARD LVCMOS33 [get_ports btnL]
#set_property PACKAGE_PIN T17 [get_ports btnR]
	#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
#set_property PACKAGE_PIN U17 [get_ports btnD]
	#set_property IOSTANDARD LVCMOS33 [get_ports btnD]
